services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-grupoemi
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build: .
    image: grupoemi:v1.0
    container_name: grupoemi
    restart: always
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - laravel
    environment:
      - DB_HOST=mysql

  mysql:
    container_name: mysql-grupoemi
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grupoemi
      MYSQL_USER: grupoemi_user
      MYSQL_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-grupoemi
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel
      
volumes:
  mysql_data: {}
    
networks:
  laravel: